module.exports = [
  {
    slug: "medicina",
    nombre: "Medicina",
    emoji: "🟣",
    color: "#7c4fa0",
    colorSuave: "#e6dcef",
    descripcion: "El cuerpo, sus señales y por qué hace lo que hace.",
  },
  {
    slug: "universo",
    nombre: "Universo",
    emoji: "🔵",
    color: "#3a6ea5",
    colorSuave: "#dbe6f0",
    descripcion: "El cosmos, la luz y las preguntas más grandes.",
  },
  {
    slug: "ciencia",
    nombre: "Ciencia general",
    emoji: "🟢",
    color: "#4c8c62",
    colorSuave: "#dcebe1",
    descripcion: "Cómo funciona el mundo, un mecanismo a la vez.",
  },
  {
    slug: "reflexiones",
    nombre: "Reflexiones",
    emoji: "🟡",
    color: "#b8912f",
    colorSuave: "#f0e7d2",
    descripcion: "Pausas para pensar más despacio.",
  },
  {
    slug: "tecnologia",
    nombre: "Tecnología y futuro",
    emoji: "🟠",
    color: "#c1652f",
    colorSuave: "#f1ddce",
    descripcion: "Lo nuevo, y lo que significa para el futuro.",
  },
];
